# Add a .env file
# Format: PRIVATE_KEY = 0xff24035b746538dcf76e37774e8865beaa17d1a0d8fc472fe78958f7d8e6917f
dotenv: .env


dependencies:
  # <Creator>/<contract-name>@version


compiler:
  solc:
    remappings:
      # @name='<Creator>/<contract-name>@version'


# Command to create a new (Ganache Forked) Network with the ID 'bsc-fork'
# brownie networks add Ethereum id=bsc-fork host=http://127.0.0.1:8545 chainid=1337 name=BSC
#  └─BSC
#    ├─id: bsc-fork
#    ├─chainid: 1337
#    └─host: http://127.0.0.1:8545
networks:
  default: bsc-fork
  bsc-fork:
    mnemonic: proud ghost pole gym device glide milk easy wise quality iron steak
    verify: False
  bsc-test:
    verify: False
  bsc-main:
    verify: False


wallets:
  from_key: ${PRIVATE_KEY}
