# Add a .env file
# Format:
# - PRIVATE_KEY = 0x.....
# - BSCSCAN_TOKEN = AA...
dotenv: .env


dependencies:
  # <Creator>/<contract-name>@version


compiler:
  solc:
    remappings:
      # @name='<Creator>/<contract-name>@version'


# Command to create a new (Ganache Forked) Network with the ID 'bsc-fork'
# brownie networks add Ethereum id=bsc-fork host=http://127.0.0.1:8545 chainid=1337 name=BSC
#  └─BSC
#    ├─id: bsc-fork
#    ├─chainid: 1337
#    └─host: http://127.0.0.1:8545
networks:
  default: bsc-fork
  bsc-fork:
    mnemonic: ${MNEMONIC}
    verify: False
  bsc-test:
    verify: False
  bsc-main:
    verify: True


wallets:
  from_key: ${PRIVATE_KEY}
